"""Local stubs for the ddgs package (PyPI: ddgs); satisfies Pyright/Pylance."""
from collections.abc import Iterator
from typing import Any

class DDGS:
    def __enter__(self) -> DDGS: ...
    def __exit__(self, *args: object) -> None: ...
    def text(self, query: str, *, max_results: int = 10) -> Iterator[dict[str, Any]]: ...
